// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/MohdAhzan/StreamVideoGRPC/VIDEO_STREAM_SVC/pkg/api"
	"github.com/MohdAhzan/StreamVideoGRPC/VIDEO_STREAM_SVC/pkg/api/service"
	"github.com/MohdAhzan/StreamVideoGRPC/VIDEO_STREAM_SVC/pkg/config"
	"github.com/MohdAhzan/StreamVideoGRPC/VIDEO_STREAM_SVC/pkg/db"
	"github.com/MohdAhzan/StreamVideoGRPC/VIDEO_STREAM_SVC/pkg/repository"
)

// Injectors from wire.go:

func InitializeService(c *config.Config) (*api.Server, error) {
	gormDB, err := db.Initdb(c)
	if err != nil {
		return nil, err
	}
	videoRepo := repository.NewVideoRepo(gormDB)
	videoServiceServer := service.NewVideoServer(videoRepo)
	server, err := api.NewgrpcServe(c, videoServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
